### ISSUE TITLE
Angular expressions inside notification

### ISSUE THREAD

**Issue by zorzysty** [matowens/ng-notify#19]
Being able to use HTML tags inside notification is great. How about taking it one step further and allow to use angular expressions inside the template, so instead of: 
`ngNotify.set('User ' + vm.username + ' was added successfully with id ' + vm.id + '!', 'success');`
you'd be able to write:
`ngNotify.set('User {{vm.username}} was added successfully with id {{vm.id}}!', 'success');`
which is slightly more readable and more 'angular-way'?

**Comment by matowens** [comment]
Hey @zorzysty, I'm not too sure that's something we'd be able to do well within ng-notify.  We'd need to know the values for each of those params in your string within ng-notify so that we could compile them properly, but those values are most likely sitting within you controller, out of reach.

If you really wanted to use curly braces to compile your messages, you could potentially create a generic method that could do something similar to what's shown here:

https://docs.angularjs.org/api/ng/service/$interpolate

Eg:

var $interpolate = ...; // injected
var yourMessage = $interpolate('User {{ vm.username }} was added successfully with id {{ vm.id }}!');
ngNotify.set(yourMessage, 'success');

I've not messed around with this so I'm not entirely sure this would run as you'd hope.  I hope this helps you out.
