### ISSUE TITLE
Callback when after close och duration period?

### ISSUE THREAD

**Issue by mrweiland** [matowens/ng-notify#20]
But is it possible to add some callback after duration period or close of notify message? 

Lets say i want to redirect user after close och duration.. 

Thanks for a great notification :+1:

**Comment by maksad** [comment]
Ref: https://github.com/matowens/ng-notify/issues/21

**Comment by matowens** [comment]
Hey @mrweiland, sorry for the long delay, but we've added a new param that you can pass to the config in order to remove the button from displaying on sticky notifications.  This allows you to display the notification indefinitely until you're ready to close it and move on.

Does this give you the freedom that you're looking for here?  You could show the notification in your app, perform any number of tasks or wait for X number of seconds, then dismiss the notification and redirect the user.

Let me know if this helps.  I'd also be happy to take a look at a pull request if you had something more specific in mind.  Thanks for the feedback!
