### ISSUE TITLE
Testing with protractor - change $timeout to $interval

### ISSUE THREAD

**Issue by adrianolobo** [matowens/ng-notify#32]
Hi,

Is it possible to change the $timeout calls to $interval? Because I'am doing e2e testing and want to check if the notify message is showing correct, but as ng-notify uses $timeout, protractor will wait until the $timeout call is finished to continue with testing, It causes some flakyness because selenium driver will have to catch the message when its hiding.

I don't know if I was clear with my explanation, but here is an issue about this behavior: https://github.com/angular/protractor/issues/169 .

**Comment by matowens** [comment]
Looking through that thread, it appears that there is a bug in protractor that's preventing it from testing correctly.  I don't think reworking ngNotify and it's existing tests to appease a bug in another testing framework is a good idea or good use of dev time.

ngNotify uses angular mock in a couple tests that check to see if the correct message is displaying.  Those tests run by using the 'grunt test' command.  I'd recommend expanding on those existing test cases, or even just using those tests directly, instead of trying to code to fit within the limits of protractor.

There's some info on angular mock here https://docs.angularjs.org/api/ngMock, with support for both $timeout and $interval.
